name: elena_project44
description: Suivi biberons / couches / dodos pour parents fatigués. Offline-first.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  #screen_brightness: ^1.0.1
  flutter_svg: ^2.0.10   # rendu des SVG via SvgPicture.asset
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  stomp_dart_client: ^2.0.0
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
